{
 "title": "Hive - HiveMetaStore",
 "tags": [ "hive" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "components", "query": "hivemetastore" },
   { "name": "hosts", "label": "Hosts", "query": "hosts.$cluster" }
  ]
 },
 "panels": [
  { "title": "API Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API call times - Health Check roundtrip (get_databases)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "typical",
     "app": "hivemetastore",
     "downsampleAggregator": "avg",
     "metric": "default.General.api_get_all_databases_75thpercentile",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "max",
     "alias": "max",
     "app": "hivemetastore",
     "downsampleAggregator": "avg",
     "metric": "default.General.api_get_all_databases_999thpercentile",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "API call times - Moderate size call (get_partitions_by_names)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "typical",
     "app": "hivemetastore",
     "downsampleAggregator": "avg",
     "metric": "default.General.api_get_",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "max",
     "alias": "max",
     "app": "hivemetastore",
     "downsampleAggregator": "avg",
     "metric": "default.General.api_get_partitions_by_names_999thpercentile",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Memory Pressure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "App Stop times (due to GC)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "GC app stop time",
       "app": "hivemetastore",
       "downsampleAggregator": "avg",
       "metric": "default.General.jvm.pause.extraSleepTime",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Heap Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "MemHeapMax",
       "app": "hivemetastore",
       "downsampleAggregator": "avg",
       "metric": "default.General.heap.max",
       "precision": "default"
      },
      {
       "aggregator": "max",
       "alias": "MemHeapUsed",
       "app": "hivemetastore",
       "downsampleAggregator": "avg",
       "metric": "default.General.heap.used",
       "precision": "default"
      },
      {
       "aggregator": "max",
       "alias": "MemHeapCommitted",
       "app": "hivemetastore",
       "downsampleAggregator": "avg",
       "metric": "default.General.heap.committed",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Off-Heap Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "MemNonHeapMax",
       "app": "hivemetastore",
       "downsampleAggregator": "avg",
       "metric": "default.General.non-heap.max",
       "precision": "default"
      },
      {
       "aggregator": "max",
       "alias": "MemNonHeapUsed",
       "app": "hivemetastore",
       "downsampleAggregator": "avg",
       "metric": "default.General.non-heap.used",
       "precision": "default"
      },
      {
       "aggregator": "max",
       "alias": "MemNonHeapCommitted",
       "app": "hivemetastore",
       "downsampleAggregator": "avg",
       "metric": "default.General.non-heap.committed",
       "precision": "default"
      }
     ]
    }
   ]
  }
 ]
}