{
 "title": "Hive - Home",
 "tags": [ "hive" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Warehouse size - at a glance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DB count at startup",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "aggregator": "max",
     "alias": "DB count",
     "app": "hivemetastore",
     "downsampleAggregator": "avg",
     "metric": "default.General.init_total_count_dbs",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Table count at startup",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "aggregator": "max",
     "alias": "Table Count",
     "app": "hivemetastore",
     "downsampleAggregator": "avg",
     "metric": "default.General.init_total_count_tables",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Partition count at startup",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "aggregator": "max",
     "alias": "DB count",
     "app": "hivemetastore",
     "downsampleAggregator": "avg",
     "metric": "default.General.init_total_count_partitions",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Warehouse size - realtime growth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "#tables created (ongoing)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "sum",
       "alias": "#tables created on HMS",
       "app": "hivemetastore",
       "downsampleAggregator": "avg",
       "metric": "default.General.api_create_table_req_count",
       "precision": "default"
      },
      {
       "aggregator": "sum",
       "alias": "#tables created on HS2",
       "app": "hiveserver2",
       "downsampleAggregator": "avg",
       "metric": "default.General.api_create_table_count",
       "precision": "default"
      }
     ]
    },
    {
     "title": "#partitions created (ongoing)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "sum",
       "alias": "#partitions created on HMS",
       "app": "hivemetastore",
       "downsampleAggregator": "avg",
       "metric": "default.General.create_total_count_partitions",
       "precision": "default"
      },
      {
       "aggregator": "sum",
       "alias": "#partitions created on HS2",
       "app": "hiveserver2",
       "downsampleAggregator": "avg",
       "metric": "default.General.create_total_count_partitions",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Pressure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "HiveMetaStore Memory - Max",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "MemHeapMax",
       "app": "hivemetastore",
       "downsampleAggregator": "avg",
       "metric": "default.General.heap.max",
       "precision": "default"
      },
      {
       "aggregator": "max",
       "alias": "MemHeapUsed",
       "app": "hivemetastore",
       "downsampleAggregator": "avg",
       "metric": "default.General.heap.used",
       "precision": "default"
      },
      {
       "aggregator": "max",
       "alias": "MemHeapCommitted",
       "app": "hivemetastore",
       "downsampleAggregator": "avg",
       "metric": "default.General.heap.committed",
       "precision": "default"
      }
     ]
    },
    {
     "title": "HiveServer2 Memory - Max",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "MemHeapMax",
       "app": "hiveserver2",
       "downsampleAggregator": "avg",
       "metric": "default.General.memory.heap.max",
       "precision": "default"
      },
      {
       "aggregator": "max",
       "alias": "MemHeapUsed",
       "app": "hiveserver2",
       "downsampleAggregator": "avg",
       "metric": "default.General.memory.heap.used",
       "precision": "default"
      },
      {
       "aggregator": "max",
       "alias": "MemHeapCommitted",
       "app": "hiveserver2",
       "downsampleAggregator": "avg",
       "metric": "default.General.memory.heap.committed",
       "precision": "default"
      }
     ]
    },
    {
     "title": "HiveMetaStore Offheap Memory - Max",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "MemNonHeapMax",
       "app": "hivemetastore",
       "downsampleAggregator": "avg",
       "metric": "default.General.non-heap.max",
       "precision": "default"
      },
      {
       "aggregator": "max",
       "alias": "MemNonHeapUsed",
       "app": "hivemetastore",
       "downsampleAggregator": "avg",
       "metric": "default.General.non-heap.used",
       "precision": "default"
      },
      {
       "aggregator": "max",
       "alias": "MemNonHeapCommitted",
       "app": "hivemetastore",
       "downsampleAggregator": "avg",
       "metric": "default.General.non-heap.committed",
       "precision": "default"
      }
     ]
    },
    {
     "title": "HiveServer2 Offheap Memory - Max",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "MemNonHeapMax",
       "app": "hiveserver2",
       "downsampleAggregator": "avg",
       "metric": "default.General.memory.non-heap.max",
       "precision": "default"
      },
      {
       "aggregator": "max",
       "alias": "MemNonHeapUsed",
       "app": "hiveserver2",
       "downsampleAggregator": "avg",
       "metric": "default.General.memory.non-heap.used",
       "precision": "default"
      },
      {
       "aggregator": "max",
       "alias": "MemNonHeapCommitted",
       "app": "hiveserver2",
       "downsampleAggregator": "avg",
       "metric": "default.General.memory.non-heap.committed",
       "precision": "default"
      }
     ]
    },
    {
     "title": "HiveMetaStore app stop times (due to GC stops)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "GC app stop times",
       "app": "hivemetastore",
       "downsampleAggregator": "avg",
       "metric": "default.General.jvm.pause.extraSleepTime",
       "precision": "default"
      }
     ]
    },
    {
     "title": "HiveServer2 app stop times (due to GC stops)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "GC app stop times",
       "app": "hiveserver2",
       "downsampleAggregator": "avg",
       "metric": "default.General.jvm.pause.extraSleepTime",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "Metastore - Call times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "API call times - Health Check roundtrip (get_all_databases)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "typical",
       "app": "hivemetastore",
       "downsampleAggregator": "avg",
       "metric": "default.General.api_get_databases_75thpercentile",
       "precision": "default"
      },
      {
       "aggregator": "max",
       "alias": "max",
       "app": "hivemetastore",
       "downsampleAggregator": "avg",
       "metric": "default.General.api_get_databases_999thpercentile",
       "precision": "default"
      }
     ]
    },
    {
     "title": "API call times - Moderate size call (get_partitions_by_names)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "typical",
       "app": "hivemetastore",
       "downsampleAggregator": "avg",
       "metric": "default.General.api_get_partitions_75thpercentile",
       "precision": "default"
      },
      {
       "aggregator": "max",
       "alias": "max",
       "app": "hivemetastore",
       "downsampleAggregator": "avg",
       "metric": "default.General.api_get_partitions_999thpercentile",
       "precision": "default"
      }
     ]
    }
   ]
  }
 ]
}