{
 "title": "Hive - HiveServer2",
 "tags": [ "hive" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "components", "query": "hiveserver2" },
   { "name": "hosts", "label": "Hosts", "query": "hosts.$cluster" }
  ]
 },
 "panels": [
  { "title": "Memory Pressure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "App Stop times (due to GC)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "GC app stop time",
     "app": "hiveserver2",
     "downsampleAggregator": "avg",
     "metric": "default.General.jvm.pause.extraSleepTime",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "MemHeapMax",
     "app": "hiveserver2",
     "downsampleAggregator": "avg",
     "metric": "default.General.memory.heap.max",
     "precision": "default"
    },
    {
     "aggregator": "max",
     "alias": "MemHeapUsed",
     "app": "hiveserver2",
     "downsampleAggregator": "avg",
     "metric": "default.General.memory.heap.used",
     "precision": "default"
    },
    {
     "aggregator": "max",
     "alias": "MemHeapCommitted",
     "app": "hiveserver2",
     "downsampleAggregator": "avg",
     "metric": "default.General.memory.heap.committed",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Off-Heap Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "MemNonHeapMax",
     "app": "hiveserver2",
     "downsampleAggregator": "avg",
     "metric": "default.General.memory.non-heap.max",
     "precision": "default"
    },
    {
     "aggregator": "max",
     "alias": "MemNonHeapUsed",
     "app": "hiveserver2",
     "downsampleAggregator": "avg",
     "metric": "default.General.memory.non-heap.used",
     "precision": "default"
    },
    {
     "aggregator": "max",
     "alias": "MemNonHeapCommitted",
     "app": "hiveserver2",
     "downsampleAggregator": "avg",
     "metric": "default.General.memory.non-heap.committed",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active operation count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "initialized",
       "app": "hiveserver2",
       "downsampleAggregator": "avg",
       "metric": "default.General.active_calls_api_hs2_operation_INITIALIZED",
       "precision": "default"
      },
      {
       "aggregator": "max",
       "alias": "pending",
       "app": "hiveserver2",
       "downsampleAggregator": "avg",
       "metric": "default.General.active_calls_api_hs2_operation_PENDING",
       "precision": "default"
      },
      {
       "aggregator": "max",
       "alias": "running",
       "app": "hiveserver2",
       "downsampleAggregator": "avg",
       "metric": "default.General.active_calls_api_hs2_operation_RUNNING",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Completed operation states",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "sum",
       "alias": "initialized",
       "app": "hiveserver2",
       "downsampleAggregator": "avg",
       "metric": "default.General.api_hs2_operation_INITIALIZED_count",
       "precision": "default"
      },
      {
       "aggregator": "sum",
       "alias": "errored",
       "app": "hiveserver2",
       "downsampleAggregator": "avg",
       "metric": "default.General.hs2_completed_operation_ERROR",
       "precision": "default"
      },
      {
       "aggregator": "sum",
       "alias": "finished",
       "app": "hiveserver2",
       "downsampleAggregator": "avg",
       "metric": "default.General.hs2_completed_operation_FINISHED",
       "precision": "default"
      },
      {
       "aggregator": "sum",
       "alias": "closed",
       "app": "hiveserver2",
       "downsampleAggregator": "avg",
       "metric": "default.General.hs2_completed_operation_CLOSED",
       "precision": "default"
      }
     ]
    }
   ]
  }
 ]
}