{
 "title": "HDFS - TopN",
 "tags": [ "hdfs" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "components", "query": "namenode" },
   { "name": "hosts", "label": "Hosts", "query": "hosts.$cluster" }
  ]
 },
 "panels": [
  { "title": "TopN - Operations Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TopN - Total Operations Count - 1min Sliding Window",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "none",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "dfs.NNTopUserOpCounts.windowMs=60000.op=%.TotalCount",
     "precision": "default",
     "seriesAggregator": "none",
     "transform": "none"
    }
   ]
  },
  {
   "title": "TopN - Total Operations Count - 5min Sliding Window",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "none",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "dfs.NNTopUserOpCounts.windowMs=300000.op=%.TotalCount",
     "precision": "default",
     "seriesAggregator": "none",
     "transform": "none"
    }
   ]
  },
  {
   "title": "TopN - Total Operations Count - 25min Sliding Window",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "none",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "dfs.NNTopUserOpCounts.windowMs=1500000.op=%.TotalCount",
     "precision": "default",
     "seriesAggregator": "none",
     "transform": "none"
    }
   ]
  },
  {
   "title": "TOPN - Total Operations Count by User",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "TopN - Total Operations Count by User - 1min Sliding Window",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "none",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "dfs.NNTopUserOpCounts.windowMs=60000.op=*.user=%.count",
     "precision": "default",
     "seriesAggregator": "none",
     "transform": "none"
    }
   ]
  },
  {
   "title": "TopN - Total Operations Count by User - 5min Sliding Window",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "none",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "dfs.NNTopUserOpCounts.windowMs=300000.op=*.user=%.count",
     "precision": "default",
     "seriesAggregator": "none",
     "transform": "none"
    }
   ]
  },
  {
   "title": "TopN - Total Operations Count by User - 25min Sliding Window",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "none",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "dfs.NNTopUserOpCounts.windowMs=1500000.op=*.user=%.count",
     "precision": "default",
     "seriesAggregator": "none",
     "transform": "none"
    }
   ]
  },
  { "title": "TopN - Operations By User", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "TopN - Operations by User - 1min Sliding Window",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "aggregator": "none",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "dfs.NNTopUserOpCounts.windowMs=60000.op=*.TotalCount",
     "precision": "default",
     "seriesAggregator": "none",
     "transform": "none"
    },
    {
     "aggregator": "none",
     "alias": "operation by user",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "dfs.NNTopUserOpCounts.windowMs=60000.op=__%.user=%",
     "precision": "default",
     "seriesAggregator": "none",
     "transform": "none"
    }
   ]
  },
  {
   "title": "TopN - Operations by User - 5min Sliding Window",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "aggregator": "none",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "dfs.NNTopUserOpCounts.windowMs=300000.op=*.TotalCount",
     "precision": "default",
     "seriesAggregator": "none",
     "transform": "none"
    },
    {
     "aggregator": "none",
     "alias": "operation by user",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "dfs.NNTopUserOpCounts.windowMs=300000.op=__%.user=%",
     "precision": "default",
     "seriesAggregator": "none",
     "transform": "none"
    }
   ]
  },
  {
   "title": "TopN - Operations by User - 25min Sliding Window",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "aggregator": "none",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "dfs.NNTopUserOpCounts.windowMs=1500000.op=*.TotalCount",
     "precision": "default",
     "seriesAggregator": "none",
     "transform": "none"
    },
    {
     "aggregator": "none",
     "alias": "operation by user",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "dfs.NNTopUserOpCounts.windowMs=1500000.op=__%.user=%",
     "precision": "default",
     "seriesAggregator": "none",
     "transform": "none"
    }
   ]
  }
 ]
}