{
 "title": "HDFS - Home",
 "tags": [
  "hdfs",
  "home"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "components", "query": "namenode" },
   { "name": "hosts", "label": "Hosts", "query": "hosts.$cluster" }
  ]
 },
 "panels": [
  {
   "title": "Number of Files Under Construction & RPC Client Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Number of Files Under Construction",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "dfs.FSNamesystem.NumFilesUnderConstruction",
     "precision": "default"
    }
   ]
  },
  {
   "title": "RPC Client Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "rpc.rpc.client.NumOpenConnections",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Total File Operations & Capacity Used",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "Total File Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "dfs.namenode.TotalFileOps",
     "precision": "default",
     "transform": "rate"
    }
   ]
  },
  {
   "title": "Capacity Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "dfs.FSNamesystem.CapacityUsedGB",
     "precision": "default"
    },
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "dfs.FSNamesystem.CapacityTotalGB",
     "precision": "default"
    }
   ]
  },
  {
   "title": "RPC Client Port Slow Calls & HDFS Total Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }
  },
  {
   "title": "RPC Client Port Slow Calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "rpc.rpc.client.RpcSlowCalls",
     "precision": "default"
    }
   ]
  },
  {
   "title": "HDFS Total Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "dfs.FSNamesystem.TotalLoad",
     "precision": "default"
    }
   ]
  },
  { "title": "Add Block Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Add Block Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "rpcdetailed.rpcdetailed.client.AddBlockAvgTime",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Add Block Num Ops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "rpcdetailed.rpcdetailed.client.AddBlockNumOps",
     "precision": "default",
     "transform": "rate"
    }
   ]
  }
 ]
}