{
 "title": "HDFS - DataNodes",
 "tags": [ "hdfs" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "components", "query": "datanode" },
   { "name": "hosts", "label": "Hosts", "query": "hosts.$cluster" },
   { "name": "orientation", "label": "show", "query": "top,bottom" },
   { "name": "instances", "label": "instances", "query": "20,1,5,10,15,50,100" },
   { "name": "topagg", "label": "aggregator", "query": "avg,max,sum" }
  ]
 },
 "panels": [
  { "title": "Blocks Written / Read", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Blocks Written",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "datanode",
     "downsampleAggregator": "avg",
     "metric": "dfs.datanode.BlocksWritten",
     "precision": "default",
     "transform": "rate"
    }
   ]
  },
  {
   "title": "Blocks Read",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "datanode",
     "downsampleAggregator": "avg",
     "metric": "dfs.datanode.BlocksRead",
     "precision": "default",
     "transform": "rate"
    }
   ]
  },
  {
   "title": "Fsync Time / Num Ops",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fsync Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "datanode",
       "downsampleAggregator": "avg",
       "metric": "dfs.datanode.FsyncNanosAvgTime",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Fsync Num Ops",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "datanode",
       "downsampleAggregator": "avg",
       "metric": "dfs.datanode.FsyncNanosNumOps",
       "precision": "default",
       "transform": "rate"
      }
     ]
    }
   ]
  },
  {
   "title": "Data Packets Blocked / Num Ops",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Data Packet Blocked Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "datanode",
       "downsampleAggregator": "avg",
       "metric": "dfs.datanode.SendDataPacketBlockedOnNetworkNanosAvgTime",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Data Packet Blocked Num Ops",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "datanode",
       "downsampleAggregator": "avg",
       "metric": "dfs.datanode.SendDataPacketBlockedOnNetworkNanosNumOps",
       "precision": "default",
       "transform": "rate"
      }
     ]
    }
   ]
  },
  {
   "title": "Packet Transfer Blocked / Num Ops",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Packet Transfer Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "datanode",
       "downsampleAggregator": "avg",
       "metric": "dfs.datanode.SendDataPacketTransferNanosAvgTime",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Packet Transfer Num Ops",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "datanode",
       "downsampleAggregator": "avg",
       "metric": "dfs.datanode.SendDataPacketTransferNanosNumOps",
       "precision": "default",
       "transform": "rate"
      }
     ]
    }
   ]
  },
  {
   "title": "Packet Round Trip",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Packet Ack Round Trip Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "PacketAckRoundTripTime",
       "app": "datanode",
       "downsampleAggregator": "avg",
       "metric": "dfs.datanode.PacketAckRoundTripTimeNanosAvgTime",
       "precision": "default",
       "transform": "none"
      }
     ]
    },
    {
     "title": "Packet Round Trip Num Ops",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "PacketAckRoundTripNumOps",
       "app": "datanode",
       "downsampleAggregator": "avg",
       "metric": "dfs.datanode.PacketAckRoundTripTimeNanosNumOps",
       "precision": "default",
       "transform": "diff"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Errors / GC Count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "datanode",
       "downsampleAggregator": "avg",
       "metric": "dfs.datanode.DatanodeNetworkErrors",
       "precision": "default",
       "transform": "rate"
      }
     ]
    },
    {
     "title": "GC Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "datanode",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.GcCount",
       "precision": "default",
       "transform": "rate"
      }
     ]
    }
   ]
  },
  {
   "title": "GC Time / GC Time ParNew",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "datanode",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.GcTimeMillis",
       "precision": "default",
       "transform": "rate"
      }
     ]
    },
    {
     "title": "GC Time ParNew",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "datanode",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.GcTimeMillisParNew",
       "precision": "default",
       "transform": "rate"
      }
     ]
    }
   ]
  },
  {
   "title": "RPC Service Port Queue & Num Ops",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }
  },
  {
   "title": "RPC Service Port Queue Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "datanode",
     "downsampleAggregator": "avg",
     "metric": "rpc.rpc.RpcQueueTimeAvgTime",
     "precision": "default"
    }
   ]
  },
  {
   "title": "RPC Service Port Queue Num Ops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "datanode",
     "downsampleAggregator": "avg",
     "metric": "rpc.rpc.RpcQueueTimeNumOps",
     "precision": "default",
     "transform": "rate"
    }
   ]
  },
  {
   "title": "RPC Service Port Processing Time & Num Ops",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }
  },
  {
   "title": "RPC Service Port Processing Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "datanode",
     "downsampleAggregator": "avg",
     "metric": "rpc.rpc.RpcProcessingTimeAvgTime",
     "precision": "default"
    }
   ]
  },
  {
   "title": "RPC Service Port Processing Num Ops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "datanode",
     "downsampleAggregator": "avg",
     "metric": "rpc.rpc.RpcProcessingTimeNumOps",
     "precision": "default",
     "transform": "rate"
    }
   ]
  },
  {
   "title": "RPC Service Port Call Queue Length & Slow Calls",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }
  },
  {
   "title": "RPC Service Port Call Queue Length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "datanode",
     "downsampleAggregator": "avg",
     "metric": "rpc.rpc.CallQueueLength",
     "precision": "default"
    }
   ]
  },
  {
   "title": "RPC Service Port Slow Calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "datanode",
     "downsampleAggregator": "avg",
     "metric": "rpc.rpc.RpcSlowCalls",
     "precision": "default"
    }
   ]
  }
 ]
}