{
 "title": "HDFS - NameNodes",
 "tags": [ "hdfs" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "components", "query": "namenode" },
   { "name": "hosts", "label": "Hosts", "query": "hosts.$cluster" }
  ]
 },
 "panels": [
  { "title": "RPC Client Queue Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPC Client Port Queue Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "rpc.rpc.client.RpcQueueTimeAvgTime",
     "precision": "default"
    }
   ]
  },
  {
   "title": "RPC Client Port Queue Num Ops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "rpc.rpc.client.RpcQueueTimeNumOps",
     "precision": "default",
     "transform": "rate"
    }
   ]
  },
  {
   "title": "RPC Client Port Processing Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "RPC Client Port Processing Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "rpc.rpc.client.RpcProcessingTimeAvgTime",
     "precision": "default"
    }
   ]
  },
  {
   "title": "RPC Client Port Processing Num Ops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "rpc.rpc.client.RpcProcessingTimeNumOps",
     "precision": "default",
     "transform": "rate"
    }
   ]
  },
  { "title": "GC Count & Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "GC Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "jvm.JvmMetrics.GcCount",
     "precision": "default",
     "transform": "rate"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "jvm.JvmMetrics.GcTimeMillis",
     "precision": "default",
     "transform": "rate"
    }
   ]
  },
  { "title": "GC Par New", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "GC Count ParNew",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "jvm.JvmMetrics.GcCountParNew",
     "precision": "default",
     "transform": "rate"
    }
   ]
  },
  {
   "title": "GC Time ParNew",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "jvm.JvmMetrics.GcTimeMillisParNew",
     "precision": "default",
     "transform": "rate"
    }
   ]
  },
  {
   "title": "GC Extra Sleep & Warning Threshold Exceeded",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 }
  },
  {
   "title": "GC Extra Sleep Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "jvm.JvmMetrics.GcTotalExtraSleepTime",
     "precision": "default",
     "transform": "rate"
    }
   ]
  },
  {
   "title": "GC Warning Threshold Exceeded Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "jvm.JvmMetrics.GcNumWarnThresholdExceeded",
     "precision": "default",
     "transform": "rate"
    }
   ]
  },
  {
   "title": "RPC Client Port Queue & Backoff",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 }
  },
  {
   "title": "RPC Client Port Queue Length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "rpc.rpc.client.CallQueueLength",
     "precision": "default"
    }
   ]
  },
  {
   "title": "RPC Client Port Backoff",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "rpc.rpc.client.RpcClientBackoff",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Transaction Since Last Edit & Checkpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 }
  },
  {
   "title": "Transactions Since Last Edit Roll",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "dfs.FSNamesystem.TransactionsSinceLastLogRoll",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Transactions Since Last Checkpoint",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "dfs.FSNamesystem.TransactionsSinceLastCheckpoint",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Lock Queue Length & Expired Heartbeats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 }
  },
  {
   "title": "Lock Queue Length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "dfs.FSNamesystem.LockQueueLength",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Expired Heartbeats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "dfs.FSNamesystem.ExpiredHeartbeats",
     "precision": "default"
    }
   ]
  },
  { "title": "Threads Blocked / Waiting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Threads Blocked",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "jvm.JvmMetrics.ThreadsBlocked",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Threads Waiting",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "jvm.JvmMetrics.ThreadsWaiting",
     "precision": "default"
    }
   ]
  }
 ]
}