{
 "title": "HDP Home",
 "tags": [
  "home",
  "hdp"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "app": "HOST",
     "downsampleAggregator": "avg",
     "metric": "mem_used",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Cluster CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "app": "HOST",
     "downsampleAggregator": "avg",
     "metric": "cpu_user",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Cluster Load - Average",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "load_one_minute",
     "app": "HOST",
     "downsampleAggregator": "avg",
     "metric": "load_one",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "load_five_minutes",
     "app": "HOST",
     "downsampleAggregator": "avg",
     "metric": "load_five",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "load_fifteen_minutes",
     "app": "HOST",
     "downsampleAggregator": "avg",
     "metric": "load_fifteen",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Cluster Disk IO",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "app": "HOST",
     "downsampleAggregator": "avg",
     "metric": "read_bytes",
     "precision": "default",
     "transform": "rate"
    },
    {
     "aggregator": "sum",
     "app": "HOST",
     "downsampleAggregator": "avg",
     "metric": "write_bytes",
     "precision": "default",
     "transform": "rate"
    }
   ]
  },
  {
   "title": "Cluster Network IO",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "app": "HOST",
     "downsampleAggregator": "avg",
     "metric": "bytes_in",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "max",
     "app": "HOST",
     "downsampleAggregator": "avg",
     "metric": "bytes_out",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "HDFS Network IO",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "alias": "read",
     "app": "datanode",
     "downsampleAggregator": "avg",
     "metric": "dfs.datanode.BytesRead",
     "precision": "default",
     "transform": "rate"
    },
    {
     "aggregator": "sum",
     "alias": "write",
     "app": "datanode",
     "downsampleAggregator": "avg",
     "metric": "dfs.datanode.BytesWritten",
     "precision": "default",
     "transform": "rate"
    }
   ]
  },
  {
   "title": "HDFS Capacity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "alias": "used",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "dfs.FSNamesystem.CapacityUsedGB",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "sum",
     "alias": "total",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "dfs.FSNamesystem.CapacityTotalGB",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Local Disks Capacity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "alias": "total",
     "app": "HOST",
     "downsampleAggregator": "avg",
     "metric": "disk_total",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "sum",
     "alias": "used",
     "app": "HOST",
     "downsampleAggregator": "avg",
     "metric": "disk_used",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 25 },
   "format": "kbytes",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "sum",
     "app": "HOST",
     "downsampleAggregator": "avg",
     "metric": "mem_total",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Total CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "sum",
     "app": "HOST",
     "downsampleAggregator": "avg",
     "metric": "cpu_num",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 25 },
   "format": "kbytes",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "sum",
     "app": "HOST",
     "downsampleAggregator": "avg",
     "metric": "mem_used",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "CPU Cores Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 25 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "max",
     "app": "HOST",
     "downsampleAggregator": "avg",
     "metric": "cpu_user",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "HDFS Capacity Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 25 },
   "format": "gbytes",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "sum",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "metric": "dfs.FSNamesystem.CapacityUsedGB",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Num Processes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "avg",
     "app": "HOST",
     "downsampleAggregator": "avg",
     "metric": "proc_total",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Ambari Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ambari Manager Heap Memory Used",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 30 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "aggregator": "avg",
       "alias": "heap",
       "app": "ambari_server",
       "downsampleAggregator": "avg",
       "metric": "jvm.memory.heap.used",
       "precision": "default",
       "transform": "none"
      }
     ]
    },
    {
     "title": "Ambari Manager Total Memory Used",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 30 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "aggregator": "avg",
       "alias": "heap",
       "app": "ambari_server",
       "downsampleAggregator": "avg",
       "metric": "jvm.memory.total.used",
       "precision": "default",
       "transform": "none"
      }
     ]
    },
    {
     "title": "Cluster Alerts Count",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 30 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "aggregator": "avg",
       "app": "ambari_server",
       "downsampleAggregator": "avg",
       "metric": "events.alerts",
       "precision": "default",
       "transform": "none"
      }
     ]
    },
    {
     "title": "Ambari Manager Threads Count",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 30 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "aggregator": "avg",
       "alias": "heap",
       "app": "ambari_server",
       "downsampleAggregator": "avg",
       "metric": "jvm.threads.count",
       "precision": "default",
       "transform": "none"
      }
     ]
    },
    {
     "title": "HADOOP Heap/Non-Heap Memory Used,  stacked by service",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "NodeManager Heap",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.MemHeapUsedM",
       "precision": "default",
       "transform": "none"
      },
      {
       "aggregator": "avg",
       "alias": "NodeManager Non-Heap",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.MemNonHeapMaxM",
       "precision": "default",
       "transform": "none"
      },
      {
       "aggregator": "avg",
       "alias": "APPS-HISTORY Heap",
       "app": "applicationhistoryserver",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.MemHeapUsedM",
       "precision": "default",
       "transform": "none"
      },
      {
       "aggregator": "avg",
       "alias": "APPS-HISTORY Non-Heap",
       "app": "applicationhistoryserver",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.MemNonHeapUsedM",
       "precision": "default",
       "transform": "none"
      },
      {
       "aggregator": "avg",
       "alias": "JOB-HISTORY Heap",
       "app": "jobhistoryserver",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.MemHeapUsedM",
       "precision": "default",
       "transform": "none"
      },
      {
       "aggregator": "avg",
       "alias": "JOB-HISTORY Non-Heap",
       "app": "jobhistoryserver",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.MemNonHeapUsedM",
       "precision": "default",
       "transform": "none"
      },
      {
       "aggregator": "avg",
       "alias": "HDFS Heap",
       "app": "datanode",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.MemHeapUsedM",
       "precision": "default",
       "transform": "none"
      },
      {
       "aggregator": "avg",
       "alias": "HDFS Non-Heap",
       "app": "datanode",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.MemNonHeapUsedM",
       "precision": "default",
       "transform": "none"
      }
     ]
    },
    {
     "title": "Ambari Manager Heap/Non-Heap Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "heap.max",
       "app": "ambari_server",
       "metric": "jvm.memory.heap.max",
       "precision": "default",
       "transform": "none"
      },
      {
       "aggregator": "avg",
       "alias": "heap.used",
       "app": "ambari_server",
       "metric": "jvm.memory.heap.used",
       "precision": "default",
       "transform": "none"
      },
      {
       "aggregator": "avg",
       "alias": "non_heap.used",
       "app": "ambari_server",
       "metric": "jvm.memory.non-heap.used",
       "precision": "default",
       "transform": "none"
      }
     ]
    },
    {
     "title": "Cluster Events",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "total events",
       "app": "ambari_server",
       "metric": "events.total.avg",
       "precision": "default",
       "transform": "none"
      },
      {
       "aggregator": "avg",
       "alias": "alerts",
       "app": "ambari_server",
       "metric": "events.alerts.avg",
       "precision": "default",
       "transform": "none"
      },
      {
       "aggregator": "avg",
       "alias": "commands",
       "app": "ambari_server",
       "metric": "events.commands.avg",
       "precision": "default",
       "transform": "none"
      },
      {
       "aggregator": "avg",
       "alias": "event.hosts",
       "app": "ambari_server",
       "metric": "events.hosts.avg",
       "precision": "default",
       "transform": "none"
      },
      {
       "aggregator": "avg",
       "alias": "event.services",
       "app": "ambari_server",
       "metric": "events.services.avg",
       "precision": "default",
       "transform": "none"
      }
     ]
    }
   ]
  },
  {
   "title": "YARN",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "NodeManager Heap",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 30 },
     "format": "mbytes",
     "valueName": "current",
     "targets": [
      {
       "aggregator": "avg",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.MemHeapUsedM",
       "precision": "default",
       "transform": "none"
      }
     ]
    },
    {
     "title": "ResourceManager Heap",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 30 },
     "format": "mbytes",
     "valueName": "current",
     "targets": [
      {
       "aggregator": "sum",
       "alias": "failed",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.MemHeapUsedM",
       "precision": "default",
       "transform": "none"
      }
     ]
    },
    {
     "title": "JobsHistory Server Heap",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 30 },
     "format": "mbytes",
     "valueName": "current",
     "targets": [
      {
       "aggregator": "avg",
       "app": "jobhistoryserver",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.MemHeapUsedM",
       "precision": "default",
       "transform": "none"
      }
     ]
    },
    {
     "title": "Application Server Heap",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 30 },
     "format": "mbytes",
     "valueName": "current",
     "targets": [
      {
       "aggregator": "avg",
       "app": "applicationhistoryserver",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.MemHeapUsedM",
       "precision": "default",
       "transform": "none"
      }
     ]
    },
    {
     "title": "Cluster Memory Available",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 35 },
     "format": "mbytes",
     "valueName": "current",
     "targets": [
      {
       "aggregator": "sum",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.QueueMetrics.Queue=root.AvailableMB",
       "precision": "default",
       "transform": "none"
      }
     ]
    },
    {
     "title": "Cluster Nodes",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 35 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "aggregator": "sum",
       "alias": "failed",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "live_hosts",
       "precision": "default",
       "transform": "none"
      }
     ]
    },
    {
     "title": "Apps Running",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 35 },
     "format": "none",
     "valueName": "max",
     "targets": [
      {
       "aggregator": "sum",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.QueueMetrics.Queue=root.AppsRunning",
       "precision": "default",
       "transform": "none"
      }
     ]
    },
    {
     "title": "Apps Completed",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 35 },
     "format": "none",
     "valueName": "max",
     "targets": [
      {
       "aggregator": "sum",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.QueueMetrics.Queue=root.AppsCompleted",
       "precision": "default",
       "transform": "none"
      }
     ]
    },
    {
     "title": "YARN Memory Allocated",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "mbytes" }
     ],
     "targets": [
      {
       "aggregator": "sum",
       "alias": "Allocated",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.QueueMetrics.Queue=root.AllocatedMB",
       "precision": "default",
       "transform": "none"
      }
     ]
    },
    {
     "title": "YARN CPU Cores Allocated",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "aggregator": "sum",
       "alias": "CPU",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.QueueMetrics.Queue=root.AllocatedVCores",
       "precision": "default",
       "transform": "none"
      }
     ]
    },
    {
     "title": "YARN Memory Available",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "mbytes" }
     ],
     "targets": [
      {
       "aggregator": "sum",
       "alias": "YARN Mem Available",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.QueueMetrics.Queue=root.AvailableMB",
       "precision": "default",
       "transform": "none"
      }
     ]
    },
    {
     "title": "YARN Containers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "aggregator": "sum",
       "alias": "failed",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.NodeManagerMetrics.ContainersFailed",
       "precision": "default",
       "transform": "none"
      },
      {
       "aggregator": "sum",
       "alias": "allocated",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.NodeManagerMetrics.AllocatedContainers",
       "precision": "default",
       "transform": "none"
      },
      {
       "aggregator": "sum",
       "alias": "running",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.NodeManagerMetrics.ContainersRunning",
       "precision": "default",
       "transform": "none"
      }
     ]
    }
   ]
  },
  {
   "title": "HDFS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Capacity Remaining",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 31 },
     "format": "gbytes",
     "valueName": "current",
     "targets": [
      {
       "aggregator": "avg",
       "app": "namenode",
       "downsampleAggregator": "avg",
       "metric": "dfs.FSNamesystem.CapacityRemainingGB",
       "precision": "default",
       "transform": "none"
      }
     ]
    },
    {
     "title": "NameNode Heap",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 31 },
     "format": "mbytes",
     "valueName": "current",
     "targets": [
      {
       "aggregator": "avg",
       "alias": "failed",
       "app": "namenode",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.MemHeapUsedM",
       "precision": "default",
       "transform": "none"
      }
     ]
    },
    {
     "title": "DataNode Heap",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 31 },
     "format": "mbytes",
     "valueName": "current",
     "targets": [
      {
       "aggregator": "avg",
       "alias": "failed",
       "app": "datanode",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.MemHeapUsedM",
       "precision": "default",
       "transform": "none"
      }
     ]
    },
    {
     "title": "Live DataNodes",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 31 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "aggregator": "avg",
       "alias": "failed",
       "app": "namenode",
       "downsampleAggregator": "avg",
       "metric": "dfs.FSNamesystem.NumLiveDataNodes",
       "precision": "default",
       "transform": "none"
      }
     ]
    },
    {
     "title": "HDFS Blocks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "total",
       "app": "namenode",
       "metric": "dfs.FSNamesystem.BlocksTotal",
       "precision": "default",
       "transform": "none"
      },
      {
       "aggregator": "avg",
       "alias": "corrupted",
       "app": "namenode",
       "metric": "dfs.FSNamesystem.CorruptBlocks",
       "precision": "default",
       "transform": "none"
      },
      {
       "aggregator": "avg",
       "alias": "missing",
       "app": "namenode",
       "metric": "dfs.FSNamesystem.MissingBlocks",
       "precision": "default",
       "transform": "none"
      },
      {
       "aggregator": "avg",
       "alias": "under_replicated",
       "app": "namenode",
       "metric": "dfs.FSNamesystem.UnderReplicatedBlocks",
       "precision": "default",
       "transform": "none"
      },
      {
       "aggregator": "avg",
       "alias": "total_replicated",
       "app": "namenode",
       "metric": "dfs.FSNamesystem.TotalReplicatedBlocks",
       "precision": "default",
       "transform": "none"
      }
     ]
    },
    {
     "title": "HDFS Files",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "total",
       "app": "namenode",
       "metric": "dfs.FSNamesystem.FilesTotal",
       "precision": "default",
       "transform": "none"
      },
      {
       "aggregator": "avg",
       "alias": "created",
       "app": "namenode",
       "metric": "dfs.namenode.FilesCreated",
       "precision": "default",
       "transform": "none"
      },
      {
       "aggregator": "avg",
       "alias": "deleted",
       "app": "namenode",
       "metric": "dfs.namenode.FilesDeleted",
       "precision": "default",
       "transform": "none"
      },
      {
       "aggregator": "avg",
       "alias": "renamed",
       "app": "namenode",
       "metric": "dfs.namenode.FilesRenamed",
       "precision": "default",
       "transform": "none"
      }
     ]
    }
   ]
  },
  {
   "title": "Solr",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Solr Heap Utilization",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 32 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "aggregator": "avg",
       "alias": "heap",
       "app": "SOLRCLOUD",
       "downsampleAggregator": "avg",
       "metric": "solrcloud.solr.jvm.memory.heap.used",
       "precision": "default",
       "transform": "none"
      }
     ]
    },
    {
     "title": "Solr Non-Heap Utilization",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 32 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "aggregator": "avg",
       "alias": "non-heap",
       "app": "SOLRCLOUD",
       "downsampleAggregator": "avg",
       "metric": "solrcloud.solr.jvm.memory.non-heap.used",
       "precision": "default",
       "transform": "none"
      }
     ]
    },
    {
     "title": "Solr CPU Utilization",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 32 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "aggregator": "avg",
       "app": "SOLRCLOUD",
       "downsampleAggregator": "avg",
       "metric": "solrcloud.solr.jvm.os.processCpuLoad",
       "precision": "default",
       "transform": "none"
      }
     ]
    },
    {
     "title": "Solr Nodes",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 32 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "aggregator": "sum",
       "app": "SOLRCLOUD",
       "metric": "live_hosts",
       "precision": "default",
       "transform": "none"
      }
     ]
    },
    {
     "title": "Heap/Non-Heap Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "heap.max",
       "app": "SOLRCLOUD",
       "metric": "solrcloud.solr.jvm.memory.heap.max",
       "precision": "default",
       "transform": "none"
      },
      {
       "aggregator": "avg",
       "alias": "heap.used",
       "app": "SOLRCLOUD",
       "metric": "solrcloud.solr.jvm.memory.heap.used",
       "precision": "default",
       "transform": "none"
      },
      {
       "aggregator": "avg",
       "alias": "non_heap.used",
       "app": "SOLRCLOUD",
       "metric": "solrcloud.solr.jvm.memory.non-heap.used",
       "precision": "default",
       "transform": "none"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "SOLRCLOUD",
       "metric": "solrcloud.solr.jvm.os.processCpuLoad",
       "precision": "default",
       "transform": "none"
      }
     ]
    }
   ]
  },
  {
   "title": "Infra",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Infra Solr Node Heap Used",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 27 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "aggregator": "avg",
       "alias": "heap",
       "app": "ambari-infra-solr",
       "downsampleAggregator": "avg",
       "metric": "infra.solr.jvm.memory.heap.used",
       "precision": "default",
       "transform": "none"
      }
     ]
    },
    {
     "title": "Infra Solr Live Nodes",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 27 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "aggregator": "avg",
       "alias": "heap",
       "app": "ambari-infra-solr",
       "downsampleAggregator": "avg",
       "metric": "live_hosts",
       "precision": "default",
       "transform": "none"
      }
     ]
    },
    {
     "title": "Heap/Non-Heap Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "heap.max",
       "app": "ambari-infra-solr",
       "metric": "infra.solr.jvm.memory.heap.max",
       "precision": "default",
       "transform": "none"
      },
      {
       "aggregator": "avg",
       "alias": "heap.used",
       "app": "ambari-infra-solr",
       "metric": "infra.solr.jvm.memory.heap.used",
       "precision": "default",
       "transform": "none"
      },
      {
       "aggregator": "avg",
       "alias": "non_heap.used",
       "app": "ambari-infra-solr",
       "metric": "infra.solr.jvm.memory.non-heap.used",
       "precision": "default",
       "transform": "none"
      }
     ]
    }
   ]
  }
 ]
}