{
 "title": "Infra Solr Host",
 "tags": [ "infra-solr" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "components", "query": "ambari-infra-solr" },
   { "name": "hosts", "label": "Hosts", "query": "hosts.$cluster" }
  ]
 },
 "panels": [
  { "title": "JVM - CPU / MEMORY STATS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Infra Solr Process CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "aggregator": "none",
     "alias": "Process CPU utilization",
     "app": "ambari-infra-solr",
     "downsampleAggregator": "avg",
     "metric": "infra.solr.jvm.os.processCpuLoad",
     "precision": "default",
     "seriesAggregator": "none",
     "templatedHost": "%",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Infra Solr OS CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "OS CPU utilization",
     "downsampleAggregator": "avg",
     "metric": "infra.solr.jvm.os.systemCpuLoad",
     "precision": "default",
     "seriesAggregator": "none",
     "templatedHost": "%",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Infra Solr Heap Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "aggregator": "none",
     "alias": "Heap memory",
     "app": "ambari-infra-solr",
     "downsampleAggregator": "avg",
     "metric": "infra.solr.jvm.memory.heap.used",
     "precision": "default",
     "seriesAggregator": "none",
     "templatedHost": "%",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Infra Solr Non-Heap Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Non-Heap memory",
     "downsampleAggregator": "avg",
     "metric": "infra.solr.jvm.memory.non-heap.used",
     "precision": "default",
     "seriesAggregator": "none",
     "templatedHost": "%",
     "transform": "none"
    }
   ]
  },
  { "title": "JVM - THREAD STATS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Thread Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "none",
     "alias": "Thread count",
     "app": "ambari-infra-solr",
     "downsampleAggregator": "avg",
     "metric": "infra.solr.jvm.threads.count",
     "precision": "default",
     "seriesAggregator": "none",
     "templatedHost": "%",
     "transform": "none"
    }
   ]
  },
  { "title": "FILE DESCRIPTORS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Open file descriptors",
     "app": "ambari-infra-solr",
     "downsampleAggregator": "avg",
     "metric": "infra.solr.jvm.os.openFileDescriptorCount",
     "precision": "default",
     "seriesAggregator": "none",
     "templatedHost": "%",
     "transform": "none"
    }
   ]
  },
  {
   "title": "JVM - CMS GC STATS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Count Par New /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "count",
       "app": "ambari-infra-solr",
       "downsampleAggregator": "avg",
       "metric": "infra.solr.jvm.gc.ParNew.count",
       "precision": "default",
       "seriesAggregator": "none",
       "templatedHost": "%",
       "transform": "none"
      }
     ]
    },
    {
     "title": "GC Time Par New /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "time",
       "app": "ambari-infra-solr",
       "downsampleAggregator": "avg",
       "metric": "infra.solr.jvm.gc.ParNew.time",
       "precision": "default",
       "seriesAggregator": "none",
       "templatedHost": "%",
       "transform": "none"
      }
     ]
    },
    {
     "title": "GC Count CMS /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "count",
       "app": "ambari-infra-solr",
       "downsampleAggregator": "avg",
       "metric": "infra.solr.jvm.gc.ConcurrentMarkSweep.count",
       "precision": "default",
       "seriesAggregator": "none",
       "templatedHost": "%",
       "transform": "none"
      }
     ]
    },
    {
     "title": "GC Time CMS /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "time",
       "app": "ambari-infra-solr",
       "downsampleAggregator": "avg",
       "metric": "infra.solr.jvm.gc.ConcurrentMarkSweep.time",
       "precision": "default",
       "seriesAggregator": "none",
       "templatedHost": "%",
       "transform": "none"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM - G1 GC STATS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "G1 GC Young Generation Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "count",
       "app": "ambari-infra-solr",
       "downsampleAggregator": "avg",
       "metric": "infra.solr.jvm.gc.G1-Young-Generation.count",
       "precision": "default",
       "seriesAggregator": "none",
       "templatedHost": "%",
       "transform": "none"
      }
     ]
    },
    {
     "title": "G1 GC Young Generation Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "time",
       "app": "ambari-infra-solr",
       "downsampleAggregator": "avg",
       "metric": "infra.solr.jvm.gc.G1-Young-Generation.time",
       "precision": "default",
       "seriesAggregator": "none",
       "templatedHost": "%",
       "transform": "none"
      }
     ]
    },
    {
     "title": "G1 GC Old Generation Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "count",
       "app": "ambari-infra-solr",
       "downsampleAggregator": "avg",
       "metric": "infra.solr.jvm.gc.G1-Old-Generation.count",
       "precision": "default",
       "seriesAggregator": "none",
       "templatedHost": "%",
       "transform": "none"
      }
     ]
    },
    {
     "title": "G1 GC Old Generation Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "time",
       "app": "ambari-infra-solr",
       "downsampleAggregator": "avg",
       "metric": "infra.solr.jvm.gc.G1-Old-Generation.time",
       "precision": "default",
       "seriesAggregator": "none",
       "templatedHost": "%",
       "transform": "none"
      }
     ]
    }
   ]
  }
 ]
}