{
 "title": "YARN - ResourceManager",
 "tags": [ "yarn" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "components", "query": "resourcemanager" },
   { "name": "hosts", "label": "Hosts", "query": "hosts.$cluster" }
  ]
 },
 "panels": [
  { "title": "RPC Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPC Avg Processing / Queue Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "RPC Avg Processing Time",
     "app": "resourcemanager",
     "downsampleAggregator": "avg",
     "metric": "rpc.rpc.RpcProcessingTimeAvgTime",
     "precision": "default",
     "templatedHost": "%"
    },
    {
     "aggregator": "max",
     "alias": "RPC Avg Queue Time",
     "app": "resourcemanager",
     "downsampleAggregator": "avg",
     "metric": "rpc.rpc.RpcQueueTimeAvgTime",
     "precision": "default",
     "templatedHost": "%"
    }
   ]
  },
  {
   "title": "RPC Call Queue Length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "RPC CallQueue Length",
     "app": "resourcemanager",
     "downsampleAggregator": "avg",
     "metric": "rpc.rpc.CallQueueLength",
     "precision": "default",
     "templatedHost": "%"
    }
   ]
  },
  {
   "title": "RPC Slow calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "RPC Slow Calls",
     "app": "resourcemanager",
     "downsampleAggregator": "avg",
     "metric": "rpc.rpc.RpcSlowCalls",
     "precision": "default",
     "templatedHost": "%"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Mem Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "mbytes" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Max HeapMem",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.MemHeapMaxM",
       "precision": "default",
       "templatedHost": "%",
       "transform": "none"
      },
      {
       "aggregator": "max",
       "alias": "Used HeapMem",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.MemHeapUsedM",
       "precision": "default",
       "templatedHost": "%",
       "transform": "none"
      },
      {
       "aggregator": "max",
       "alias": "Committed HeapMem",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.MemHeapCommittedM",
       "precision": "default",
       "templatedHost": "%",
       "transform": "none"
      }
     ]
    },
    {
     "title": "NonHeap Mem Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "mbytes" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Used NonHeapMem",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.MemNonHeapUsedM",
       "precision": "default",
       "templatedHost": "%",
       "transform": "none"
      },
      {
       "aggregator": "max",
       "alias": "Committed NonHeapMem",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.MemNonHeapCommittedM",
       "precision": "default",
       "templatedHost": "%",
       "transform": "none"
      }
     ]
    }
   ]
  },
  {
   "title": "GC Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "GC Count",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.GcCount",
       "precision": "default",
       "templatedHost": "%",
       "transform": "diff"
      }
     ]
    },
    {
     "title": "GcTime",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "GC Time",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.GcTimeMillis",
       "precision": "default",
       "templatedHost": "%",
       "transform": "diff"
      }
     ]
    }
   ]
  },
  {
   "title": "Log Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log Error/ Fatal",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Log Errors",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.LogError",
       "precision": "default",
       "templatedHost": "%"
      },
      {
       "aggregator": "max",
       "alias": "Log Fatal",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.LogFatal",
       "precision": "default",
       "templatedHost": "%"
      }
     ]
    }
   ]
  },
  {
   "title": "Authorization & Authentication Failures",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPC Authorization Failures",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "RPC Authorization Failures",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "rpc.rpc.RpcAuthorizationFailures",
       "precision": "default",
       "templatedHost": "%"
      }
     ]
    },
    {
     "title": "RPC Authentication Failures",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "RPC Authentication Failures",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "rpc.rpc.RpcAuthenticationFailures",
       "precision": "default",
       "templatedHost": "%"
      }
     ]
    }
   ]
  }
 ]
}