{
 "title": "YARN - NodeManagers",
 "tags": [ "yarn" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "components", "query": "nodemanager" },
   { "name": "hosts", "label": "Hosts", "query": "hosts.$cluster" },
   { "name": "orientation", "label": "show", "query": "top,bottom" },
   { "name": "instances", "label": "instances", "query": "20,1,5,10,15,50,100" },
   { "name": "topagg", "label": "aggregator", "query": "avg,max,sum" }
  ]
 },
 "panels": [
  { "title": "Num Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Containers Running",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "Containers Running",
     "app": "nodemanager",
     "downsampleAggregator": "avg",
     "metric": "yarn.NodeManagerMetrics.ContainersRunning",
     "precision": "default",
     "qmetric": "resourcemanager",
     "queue": "yarn.NodeManagerMetrics.ContainersRunning",
     "templatedHost": "%"
    }
   ]
  },
  {
   "title": "Containers Failed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "Containers Failed",
     "app": "nodemanager",
     "downsampleAggregator": "avg",
     "metric": "yarn.NodeManagerMetrics.ContainersFailed",
     "precision": "default",
     "templatedHost": "%",
     "transform": "diff"
    }
   ]
  },
  {
   "title": "Containers Killed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "Containers Killed",
     "app": "nodemanager",
     "downsampleAggregator": "avg",
     "metric": "yarn.NodeManagerMetrics.ContainersKilled",
     "precision": "default",
     "templatedHost": "%",
     "transform": "diff"
    }
   ]
  },
  {
   "title": "Containers Completed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "Containers Completed",
     "app": "nodemanager",
     "downsampleAggregator": "avg",
     "metric": "yarn.NodeManagerMetrics.ContainersCompleted",
     "precision": "default",
     "templatedHost": "%",
     "transform": "diff"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Available",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "gbytes" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Memory Available",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.NodeManagerMetrics.AvailableGB",
       "precision": "default",
       "templatedHost": "%"
      }
     ]
    },
    {
     "title": "Used Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "gbytes" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Used Memory",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.NodeManagerMetrics.AllocatedGB",
       "precision": "default",
       "qmetric": "resourcemanager",
       "queue": "yarn.NodeManagerMetrics.AllocatedGB",
       "templatedHost": "%"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Utilization for Good Log Dirs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Disk Utilization for Good Log Dirs",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.NodeManagerMetrics.GoodLogDirsDiskUtilizationPerc",
       "precision": "default",
       "qmetric": "resourcemanager",
       "queue": "yarn.NodeManagerMetrics.GoodLogDirsDiskUtilizationPerc",
       "templatedHost": "%",
       "transform": "none"
      }
     ]
    },
    {
     "title": "Disk Utilization for Good Local Dirs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "GoodLocalDirsDiskUtilization",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.NodeManagerMetrics.GoodLocalDirsDiskUtilizationPerc",
       "precision": "default",
       "templatedHost": "%",
       "transform": "none"
      }
     ]
    },
    {
     "title": "Bad Log Dirs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Bad Log Dirs",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.NodeManagerMetrics.BadLogDirs",
       "precision": "default",
       "qmetric": "resourcemanager",
       "queue": "yarn.NodeManagerMetrics.BadLogDirs",
       "templatedHost": "%"
      }
     ]
    },
    {
     "title": "Bad Local Dirs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Bad Local Dirs",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.NodeManagerMetrics.BadLocalDirs",
       "precision": "default",
       "templatedHost": "%"
      }
     ]
    }
   ]
  },
  {
   "title": "Avg Container Launch Delay",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg Container Launch Delay",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Avg Container Launch Delay",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.NodeManagerMetrics.ContainerLaunchDurationAvgTime",
       "precision": "default",
       "templatedHost": "%"
      }
     ]
    }
   ]
  },
  {
   "title": "RPC Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPC Avg Processing Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "RPC Avg Processing Time",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "rpc.rpc.RpcProcessingTimeAvgTime",
       "precision": "default",
       "templatedHost": "%"
      }
     ]
    },
    {
     "title": "RPC Avg Queue Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "RPC Avg Queue Time",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "rpc.rpc.RpcQueueTimeAvgTime",
       "precision": "default",
       "templatedHost": "%"
      }
     ]
    },
    {
     "title": "RPC Call Queue Length",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "RPC Call Queue Length",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "rpc.rpc.CallQueueLength",
       "precision": "default",
       "templatedHost": "%"
      }
     ]
    },
    {
     "title": "RPC Slow Calls",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "RPC Slow Calls",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "rpc.rpc.RpcSlowCalls",
       "precision": "default",
       "templatedHost": "%"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Mem Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "mbytes" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Max HeapMem",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.MemHeapMaxM",
       "precision": "default",
       "templatedHost": "%"
      },
      {
       "aggregator": "max",
       "alias": "Used HeapMem",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.MemHeapUsedM",
       "precision": "default",
       "templatedHost": "%"
      }
     ]
    },
    {
     "title": "NonHeap Mem Used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "mbytes" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "NonHeap Mem Used",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.MemNonHeapUsedM",
       "precision": "default",
       "templatedHost": "%"
      }
     ]
    },
    {
     "title": "GC Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "GC Count",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.GcCount",
       "precision": "minutes",
       "templatedHost": "%"
      }
     ]
    },
    {
     "title": "GC Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "GC Time",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.GcTimeMillis",
       "precision": "default",
       "templatedHost": "%"
      }
     ]
    }
   ]
  },
  {
   "title": "LOG4J Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "LOG ERROR",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "LOG Error",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.LogError",
       "precision": "default",
       "templatedHost": "%"
      }
     ]
    },
    {
     "title": "LOG FATAL",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "LOG FATAL",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.LogFatal",
       "precision": "default",
       "templatedHost": "%"
      }
     ]
    }
   ]
  }
 ]
}