{
 "title": "YARN - Queues",
 "tags": [ "yarn" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "queue", "query": "yarnqueues" }
  ]
 },
 "panels": [
  { "title": "Num Apps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Apps Running",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "Apps Running",
     "app": "resourcemanager",
     "downsampleAggregator": "avg",
     "metric": "yarn.QueueMetrics.Queue=root.AppsRunning",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Apps Pending",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "Apps Pending",
     "app": "resourcemanager",
     "downsampleAggregator": "avg",
     "metric": "yarn.QueueMetrics.Queue=root.AppsPending",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Apps Completed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "Apps Completed",
     "app": "resourcemanager",
     "downsampleAggregator": "avg",
     "metric": "yarn.QueueMetrics.Queue=root.AppsCompleted",
     "precision": "default",
     "transform": "diff"
    }
   ]
  },
  {
   "title": "Apps Failed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "Apps Failed",
     "app": "resourcemanager",
     "downsampleAggregator": "avg",
     "metric": "yarn.QueueMetrics.Queue=root.AppsFailed",
     "precision": "default",
     "transform": "diff"
    }
   ]
  },
  {
   "title": "Apps Killed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "Apps Killed",
     "app": "resourcemanager",
     "downsampleAggregator": "avg",
     "metric": "yarn.QueueMetrics.Queue=root.AppsKilled",
     "precision": "default",
     "transform": "diff"
    }
   ]
  },
  {
   "title": "Apps Submitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "Apps Submitted",
     "app": "resourcemanager",
     "downsampleAggregator": "avg",
     "metric": "yarn.QueueMetrics.Queue=root.AppsSubmitted",
     "precision": "default",
     "transform": "diff"
    }
   ]
  },
  {
   "title": "Num Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers Running",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Containers Running",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.QueueMetrics.Queue=root.AllocatedContainers",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Containers Pending",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Pending Containers",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.QueueMetrics.Queue=root.PendingContainers",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Containers Reserved",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Containers Reserved",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.QueueMetrics.Queue=root.default.ReservedContainers",
       "precision": "default",
       "transform": "none"
      }
     ]
    },
    {
     "title": "Containers Allocated",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Containers Allocated",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.QueueMetrics.Queue=root.AggregateContainersAllocated",
       "precision": "default",
       "transform": "diff"
      }
     ]
    },
    {
     "title": "Node Local Containers Allocated",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Local Containers Allocated",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.QueueMetrics.Queue=root.AggregateNodeLocalContainersAllocated",
       "precision": "default",
       "transform": "diff"
      }
     ]
    },
    {
     "title": "Rack Local Containers Allocated",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Local Containers Allocated",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.QueueMetrics.Queue=root.AggregateRackLocalContainersAllocated",
       "precision": "default",
       "transform": "diff"
      }
     ]
    },
    {
     "title": "OffSwitch Containers Allocated",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Containers Allocated",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.QueueMetrics.Queue=root.AggregateOffSwitchContainersAllocated",
       "precision": "default",
       "transform": "none"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Allocated Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "mbytes" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Allocated Memory",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.QueueMetrics.Queue=root.AllocatedMB",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Pending Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "mbytes" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Pending Memory",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.QueueMetrics.Queue=root.PendingMB",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Available Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "mbytes" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Available Memory",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.QueueMetrics.Queue=root.AvailableMB",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Reserved Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "mbytes" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Reserved Memory",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.QueueMetrics.Queue=root.default.ReservedMB",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Memory used by AM",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "mbytes" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Max AM Mem",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.QueueMetrics.Queue=root.AMResourceLimitMB",
       "precision": "default"
      },
      {
       "aggregator": "max",
       "alias": "Used AM Mem",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.QueueMetrics.Queue=root.UsedAMResourceMB",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "Container Allocation Delay",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg AM Container Allocation Delay",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Avg AM Container Allocation Delay",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.QueueMetrics.Queue=root.AppAttemptFirstContainerAllocationDelayAvgTime",
       "precision": "default"
      }
     ]
    }
   ]
  }
 ]
}