{
 "title": "YARN - MR JobHistoryServer",
 "tags": [ "yarn" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "JVM Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GC Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "GC Count",
     "app": "jobhistoryserver",
     "downsampleAggregator": "avg",
     "metric": "jvm.JvmMetrics.GcCount",
     "precision": "default",
     "transform": "diff"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "GC Time",
     "app": "jobhistoryserver",
     "downsampleAggregator": "avg",
     "metric": "jvm.JvmMetrics.GcTimeMillis",
     "precision": "default",
     "transform": "diff"
    }
   ]
  },
  {
   "title": "Heap Mem Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "Max Heap",
     "app": "jobhistoryserver",
     "downsampleAggregator": "avg",
     "metric": "jvm.JvmMetrics.MemHeapMaxM",
     "precision": "default"
    },
    {
     "aggregator": "max",
     "alias": "Heap Used",
     "app": "jobhistoryserver",
     "downsampleAggregator": "avg",
     "metric": "jvm.JvmMetrics.MemHeapUsedM",
     "precision": "default"
    },
    {
     "aggregator": "max",
     "alias": "Heap Committed",
     "app": "jobhistoryserver",
     "downsampleAggregator": "avg",
     "metric": "jvm.JvmMetrics.MemHeapCommittedM",
     "precision": "default"
    }
   ]
  },
  {
   "title": "NonHeap Mem Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "NonHeap Mem Committed",
     "app": "jobhistoryserver",
     "downsampleAggregator": "avg",
     "metric": "jvm.JvmMetrics.MemNonHeapCommittedM",
     "precision": "default"
    },
    {
     "aggregator": "max",
     "alias": "NonHeap Mem Used",
     "app": "jobhistoryserver",
     "downsampleAggregator": "avg",
     "metric": "jvm.JvmMetrics.MemNonHeapUsedM",
     "precision": "default"
    }
   ]
  }
 ]
}