{
 "title": "YARN - Applications",
 "tags": [ "yarn" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Num Apps  By Elapsed Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "> 24 Hours",
     "app": "resourcemanager",
     "downsampleAggregator": "avg",
     "metric": "yarn.QueueMetrics.Queue=root.running_1440",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "max",
     "alias": "5 ~ 24 Hours",
     "app": "resourcemanager",
     "downsampleAggregator": "avg",
     "metric": "yarn.QueueMetrics.Queue=root.running_300",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "max",
     "alias": "1 ~ 5 Hours",
     "app": "resourcemanager",
     "downsampleAggregator": "avg",
     "metric": "yarn.QueueMetrics.Queue=root.running_60",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "max",
     "alias": "< 1 Hour",
     "app": "resourcemanager",
     "downsampleAggregator": "avg",
     "metric": "yarn.QueueMetrics.Queue=root.running_0",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Apps Running vs Pending",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "Running Apps",
     "app": "resourcemanager",
     "downsampleAggregator": "avg",
     "metric": "yarn.QueueMetrics.Queue=root.AppsRunning",
     "precision": "default"
    },
    {
     "aggregator": "max",
     "alias": "Pending Apps",
     "app": "resourcemanager",
     "downsampleAggregator": "avg",
     "metric": "yarn.QueueMetrics.Queue=root.AppsPending",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Apps Submitted vs Completed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "Submitted Apps",
     "app": "resourcemanager",
     "downsampleAggregator": "avg",
     "metric": "yarn.QueueMetrics.Queue=root.AppsSubmitted",
     "precision": "default",
     "transform": "diff"
    },
    {
     "aggregator": "max",
     "alias": "Completed Apps",
     "app": "resourcemanager",
     "downsampleAggregator": "avg",
     "metric": "yarn.QueueMetrics.Queue=root.AppsCompleted",
     "precision": "default",
     "transform": "diff"
    }
   ]
  },
  {
   "title": "Avg AM Launch Delay",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "Avg AM Launch Delay",
     "app": "resourcemanager",
     "downsampleAggregator": "avg",
     "metric": "yarn.ClusterMetrics.AMLaunchDelayAvgTime",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Avg AM Register Delay",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "Avg AM Register Delay",
     "app": "resourcemanager",
     "downsampleAggregator": "avg",
     "metric": "yarn.ClusterMetrics.AMRegisterDelayAvgTime",
     "precision": "default"
    }
   ]
  }
 ]
}