{
 "title": "Solr Cloud Cores",
 "tags": [ "solrcloud" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Cores", "query": "solrcloud_core" }
  ]
 },
 "panels": [
  { "title": "Indexing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Index Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "aggregator": "none",
     "alias": "size",
     "app": "SOLRCLOUD",
     "downsampleAggregator": "avg",
     "metric": "solrcloud.solr.core.*.INDEX.sizeInBytes",
     "precision": "default",
     "seriesAggregator": "none",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Indexing Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "adds",
     "app": "SOLRCLOUD",
     "downsampleAggregator": "avg",
     "metric": "solrcloud.solr.core.*.UPDATE.updateHandler.adds",
     "precision": "default",
     "sCore": "history.shard1.replica_n1",
     "sCoreMetric": "solrcloud.solr.core.history.shard1.replica_n1.UPDATE.updateHandler.adds",
     "seriesAggregator": "none",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Deletes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "deletes by id",
     "app": "SOLRCLOUD",
     "downsampleAggregator": "avg",
     "metric": "solrcloud.solr.core.*.UPDATE.updateHandler.deletesById",
     "precision": "default",
     "sCore": "history.shard1.replica_n1",
     "sCoreMetric": "solrcloud.solr.core.history.shard1.replica_n1.UPDATE.updateHandler.deletesById",
     "seriesAggregator": "none",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "deletes by query",
     "app": "SOLRCLOUD",
     "downsampleAggregator": "avg",
     "metric": "solrcloud.solr.core.*.UPDATE.updateHandler.deletesByQuery",
     "precision": "default",
     "sCore": "history.shard1.replica_n1",
     "sCoreMetric": "solrcloud.solr.core.history.shard1.replica_n1.UPDATE.updateHandler.deletesByQuery",
     "seriesAggregator": "none",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "errors",
     "app": "SOLRCLOUD",
     "downsampleAggregator": "avg",
     "metric": "solrcloud.solr.core.*.UPDATE.updateHandler.errors",
     "precision": "default",
     "sCore": "history.shard1.replica_n1",
     "sCoreMetric": "solrcloud.solr.core.history.shard1.replica_n1.UPDATE.updateHandler.errors",
     "seriesAggregator": "none",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Pending Documents",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "docs pending",
     "app": "SOLRCLOUD",
     "downsampleAggregator": "avg",
     "metric": "solrcloud.solr.core.*.UPDATE.updateHandler.docsPending",
     "precision": "default",
     "sCore": "history.shard1.replica_n1",
     "sCoreMetric": "solrcloud.solr.core.history.shard1.replica_n1.UPDATE.updateHandler.docsPending",
     "seriesAggregator": "none",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Select Handler Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "average requests per second",
     "app": "SOLRCLOUD",
     "downsampleAggregator": "avg",
     "metric": "solrcloud.solr.core.*.QUERY./select.requestTimes.avgRequestsPerSecond",
     "precision": "default",
     "sCore": "history.shard1.replica_n1",
     "sCoreMetric": "solrcloud.solr.core.history.shard1.replica_n1.QUERY./select.requestTimes.avgRequestsPerSecond",
     "seriesAggregator": "none",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Time Per Select Handler Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "average time per requests",
     "app": "SOLRCLOUD",
     "downsampleAggregator": "avg",
     "metric": "solrcloud.solr.core.*.QUERY./select.requestTimes.avgTimePerRequest",
     "precision": "default",
     "sCore": "history.shard1.replica_n1",
     "sCoreMetric": "solrcloud.solr.core.history.shard1.replica_n1.QUERY./select.requestTimes.avgTimePerRequest",
     "seriesAggregator": "none",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "median request time",
     "app": "SOLRCLOUD",
     "downsampleAggregator": "avg",
     "metric": "solrcloud.solr.core.*.QUERY./select.requestTimes.medianRequestTime",
     "precision": "default",
     "sCore": "history.shard1.replica_n1",
     "sCoreMetric": "solrcloud.solr.core.history.shard1.replica_n1.QUERY./select.requestTimes.medianRequestTime",
     "seriesAggregator": "none",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Update Handler Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "average requests per second",
     "app": "SOLRCLOUD",
     "downsampleAggregator": "avg",
     "metric": "solrcloud.solr.core.*.UPDATE./update.requestTimes.avgRequestsPerSecond",
     "precision": "default",
     "sCore": "history.shard1.replica_n1",
     "sCoreMetric": "solrcloud.solr.core.history.shard1.replica_n1.UPDATE./update.requestTimes.avgRequestsPerSecond",
     "seriesAggregator": "none",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Time Per Update Handler Request",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "average time per request",
     "app": "SOLRCLOUD",
     "downsampleAggregator": "avg",
     "metric": "solrcloud.solr.core.*.UPDATE./update.requestTimes.avgTimePerRequest",
     "precision": "default",
     "sCore": "history.shard1.replica_n1",
     "sCoreMetric": "solrcloud.solr.core.history.shard1.replica_n1.UPDATE./update.requestTimes.avgTimePerRequest",
     "seriesAggregator": "none",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "median request time",
     "app": "SOLRCLOUD",
     "downsampleAggregator": "avg",
     "metric": "solrcloud.solr.core.*.UPDATE./update.requestTimes.medianRequestTime",
     "precision": "default",
     "sCore": "history.shard1.replica_n1",
     "sCoreMetric": "solrcloud.solr.core.history.shard1.replica_n1.UPDATE./update.requestTimes.medianRequestTime",
     "seriesAggregator": "none",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Get Handler Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "average requests per second",
     "app": "SOLRCLOUD",
     "downsampleAggregator": "avg",
     "metric": "solrcloud.solr.core.*.QUERY./get.requestTimes.avgRequestsPerSecond",
     "precision": "default",
     "sCore": "history.shard1.replica_n1",
     "sCoreMetric": "solrcloud.solr.core.history.shard1.replica_n1.QUERY./get.requestTimes.avgRequestsPerSecond",
     "seriesAggregator": "none",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Time Per Get Handler Request",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "average time per requests",
     "app": "SOLRCLOUD",
     "downsampleAggregator": "avg",
     "metric": "solrcloud.solr.core.*.QUERY./get.requestTimes.avgTimePerRequest",
     "precision": "default",
     "sCore": "history.shard1.replica_n1",
     "sCoreMetric": "solrcloud.solr.core.history.shard1.replica_n1.QUERY./get.requestTimes.avgTimePerRequest",
     "seriesAggregator": "none",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "median request time",
     "app": "SOLRCLOUD",
     "downsampleAggregator": "avg",
     "metric": "solrcloud.solr.core.*.QUERY./get.requestTimes.medianRequestTime",
     "precision": "default",
     "sCore": "history.shard1.replica_n1",
     "sCoreMetric": "solrcloud.solr.core.history.shard1.replica_n1.QUERY./get.requestTimes.medianRequestTime",
     "seriesAggregator": "none",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Luke Handler Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "average requests per second",
     "app": "SOLRCLOUD",
     "downsampleAggregator": "avg",
     "metric": "solrcloud.solr.core.*.ADMIN./admin/luke.requestTimes.avgRequestsPerSecond",
     "precision": "default",
     "sCore": "history.shard1.replica_n1",
     "sCoreMetric": "solrcloud.solr.core.history.shard1.replica_n1.ADMIN./admin/luke.requestTimes.avgRequestsPerSecond",
     "seriesAggregator": "none",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Time Per Luke Handler Request",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "average time per request",
     "app": "SOLRCLOUD",
     "downsampleAggregator": "avg",
     "metric": "solrcloud.solr.core.*.ADMIN./admin/luke.requestTimes.avgTimePerRequest",
     "precision": "default",
     "sCore": "history.shard1.replica_n1",
     "sCoreMetric": "solrcloud.solr.core.history.shard1.replica_n1.ADMIN./admin/luke.requestTimes.avgTimePerRequest",
     "seriesAggregator": "none",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "median request time",
     "app": "SOLRCLOUD",
     "downsampleAggregator": "avg",
     "metric": "solrcloud.solr.core.*.ADMIN./admin/luke.requestTimes.medianRequestTime",
     "precision": "default",
     "sCore": "history.shard1.replica_n1",
     "sCoreMetric": "solrcloud.solr.core.history.shard1.replica_n1.ADMIN./admin/luke.requestTimes.medianRequestTime",
     "seriesAggregator": "none",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Query Handler Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "average requests per second",
     "app": "SOLRCLOUD",
     "downsampleAggregator": "avg",
     "metric": "solrcloud.solr.core.*.QUERY./get.requestTimes.avgRequestsPerSecond",
     "precision": "default",
     "sCore": "history.shard1.replica_n1",
     "sCoreMetric": "solrcloud.solr.core.history.shard1.replica_n1.QUERY./get.requestTimes.avgRequestsPerSecond",
     "seriesAggregator": "none",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Time Per Query Handler Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "average time per request",
     "app": "SOLRCLOUD",
     "downsampleAggregator": "avg",
     "metric": "solrcloud.solr.core.*.QUERY./get.requestTimes.avgTimePerRequest",
     "precision": "default",
     "sCore": "history.shard1.replica_n1",
     "sCoreMetric": "solrcloud.solr.core.history.shard1.replica_n1.QUERY./get.requestTimes.avgTimePerRequest",
     "seriesAggregator": "none",
     "transform": "none"
    },
    {
     "aggregator": "avg",
     "alias": "median request time",
     "app": "SOLRCLOUD",
     "downsampleAggregator": "avg",
     "metric": "solrcloud.solr.core.*.QUERY./get.requestTimes.medianRequestTime",
     "precision": "default",
     "sCore": "history.shard1.replica_n1",
     "sCoreMetric": "solrcloud.solr.core.history.shard1.replica_n1.QUERY./get.requestTimes.medianRequestTime",
     "seriesAggregator": "none",
     "transform": "none"
    }
   ]
  },
  { "title": "Cashes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Filter Cache Ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "hit ratio",
     "app": "SOLRCLOUD",
     "downsampleAggregator": "avg",
     "metric": "solrcloud.solr.core.*.CACHE.searcher.filterCache.hitratio",
     "precision": "default",
     "sCore": "history.shard1.replica_n1",
     "sCoreMetric": "solrcloud.solr.core.history.shard1.replica_n1.CACHE.searcher.filterCache.hitratio",
     "seriesAggregator": "none",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Filter Cache Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "size",
     "app": "SOLRCLOUD",
     "downsampleAggregator": "avg",
     "metric": "solrcloud.solr.core.*.CACHE.searcher.filterCache.size",
     "precision": "default",
     "sCore": "history.shard1.replica_n1",
     "sCoreMetric": "solrcloud.solr.core.history.shard1.replica_n1.CACHE.searcher.filterCache.size",
     "seriesAggregator": "none",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Filter Cache Warmup Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "warmup time",
     "app": "SOLRCLOUD",
     "downsampleAggregator": "avg",
     "metric": "solrcloud.solr.core.*.CACHE.searcher.documentCache.warmupTime",
     "precision": "default",
     "sCore": "history.shard1.replica_n1",
     "sCoreMetric": "solrcloud.solr.core.history.shard1.replica_n1.CACHE.searcher.documentCache.warmupTime",
     "seriesAggregator": "none",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Document Cache Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "hit ratio",
     "app": "SOLRCLOUD",
     "downsampleAggregator": "avg",
     "metric": "solrcloud.solr.core.*.CACHE.searcher.documentCache.hitratio",
     "precision": "default",
     "sCore": "history.shard1.replica_n1",
     "sCoreMetric": "solrcloud.solr.core.history.shard1.replica_n1.CACHE.searcher.documentCache.hitratio",
     "seriesAggregator": "none",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Document Cache Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "size",
     "app": "SOLRCLOUD",
     "downsampleAggregator": "avg",
     "metric": "solrcloud.solr.core.*.CACHE.searcher.documentCache.size",
     "precision": "default",
     "sCore": "history.shard1.replica_n1",
     "sCoreMetric": "solrcloud.solr.core.history.shard1.replica_n1.CACHE.searcher.documentCache.size",
     "seriesAggregator": "none",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Document Cache Warmup Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "warmup time",
     "app": "SOLRCLOUD",
     "downsampleAggregator": "avg",
     "metric": "solrcloud.solr.core.*.CACHE.searcher.documentCache.warmupTime",
     "precision": "default",
     "sCore": "history.shard1.replica_n1",
     "sCoreMetric": "solrcloud.solr.core.history.shard1.replica_n1.CACHE.searcher.documentCache.warmupTime",
     "seriesAggregator": "none",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Query Result Cache Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "hit ratio",
     "app": "SOLRCLOUD",
     "downsampleAggregator": "avg",
     "metric": "solrcloud.solr.core.*.CACHE.searcher.queryResultCache.hitratio",
     "precision": "default",
     "sCore": "history.shard1.replica_n1",
     "sCoreMetric": "solrcloud.solr.core.history.shard1.replica_n1.CACHE.searcher.queryResultCache.hitratio",
     "seriesAggregator": "none",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Query Result Cache Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "size",
     "app": "SOLRCLOUD",
     "downsampleAggregator": "avg",
     "metric": "solrcloud.solr.core.*.CACHE.searcher.queryResultCache.size",
     "precision": "default",
     "sCore": "history.shard1.replica_n1",
     "sCoreMetric": "solrcloud.solr.core.history.shard1.replica_n1.CACHE.searcher.queryResultCache.size",
     "seriesAggregator": "none",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Query Result Cache Warmup Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "warmup time",
     "app": "SOLRCLOUD",
     "downsampleAggregator": "avg",
     "metric": "solrcloud.solr.core.*.CACHE.searcher.queryResultCache.warmupTime",
     "precision": "default",
     "sCore": "history.shard1.replica_n1",
     "sCoreMetric": "solrcloud.solr.core.history.shard1.replica_n1.CACHE.searcher.queryResultCache.warmupTime",
     "seriesAggregator": "none",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Field Cache Entry Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "count",
     "app": "SOLRCLOUD",
     "downsampleAggregator": "avg",
     "metric": "solrcloud.solr.core.*.CACHE.core.fieldCache.entries_count",
     "precision": "default",
     "sCore": "history.shard1.replica_n1",
     "sCoreMetric": "solrcloud.solr.core.history.shard1.replica_n1.CACHE.core.fieldCache.entries_count",
     "seriesAggregator": "none",
     "transform": "none"
    }
   ]
  }
 ]
}