{
 "title": "System - Servers",
 "tags": [ "system" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "components", "query": "HOST" },
   { "name": "hosts", "label": "Hosts", "query": "hosts.$cluster" },
   { "name": "orientation", "label": "show", "query": "top,bottom" },
   { "name": "instances", "label": "instances", "query": "20,1,5,10,15,50,100" },
   { "name": "topagg", "label": "aggregator", "query": "avg,max,sum" }
  ]
 },
 "panels": [
  { "title": "CPU - User / System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization - User",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "HOST",
     "downsampleAggregator": "avg",
     "metric": "cpu_user",
     "precision": "default"
    }
   ]
  },
  {
   "title": "CPU Utilization - System",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "HOST",
     "downsampleAggregator": "avg",
     "metric": "cpu_system",
     "precision": "default"
    }
   ]
  },
  {
   "title": "CPU - Nice / Idle",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization - Nice",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "cpu_nice",
       "precision": "default"
      }
     ]
    },
    {
     "title": "CPU Utilization - Idle",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "cpu_idle",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU - Iowait / Intr",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization - iowait",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "cpu_wio",
       "precision": "default"
      }
     ]
    },
    {
     "title": "CPU Utilization - Hardware Interrupt",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "cpu_intr",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU - SoftIntr / Steal",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization - Software Interrupt",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "cpu_sintr",
       "precision": "default"
      }
     ]
    },
    {
     "title": "CPU Utilization - Steal (VM)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "cpu_steal",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "System Load - 1 Minute",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Load Average - 1 Minute",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "load_one_minute",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "load_one",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "System Load - 5 Minute",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Load Average - 5 Minutes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "load_five_minutes",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "load_five",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "System Load - 15 Minute",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Load Average - 15 Minutes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "load_fifteen_minutes",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "load_fifteen",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory - Total / Used",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory - Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "mem_total",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Memory - Used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "mem_used",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory - Free / Cached",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory - Free",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "mem_free",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Memory - Cached",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "mem_cached",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory - Buffered / Shared",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory - Buffered",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "mem_buffered",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Memory - Shared",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "mem_shared",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "gbytes" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "disk_used",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Disk Free",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "gbytes" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "disk_free",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read Bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "read_bytes",
       "precision": "default",
       "transform": "rate"
      }
     ]
    },
    {
     "title": "Write Bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "write_bytes",
       "precision": "default",
       "transform": "rate"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "read_count",
       "precision": "default",
       "transform": "rate"
      }
     ]
    },
    {
     "title": "Write Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "wps" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "write_count",
       "precision": "default",
       "transform": "rate"
      }
     ]
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Bytes Received",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "bytes_in",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Network Bytes Sent",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "bytes_out",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Packets Received",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "pkts_in",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Network Packets Sent",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "pkts_out",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "Swap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Swap Space - Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "swap_total",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Swap Space - Free",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "swap_free",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "Num Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Num Processes - Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "proc_total",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Num Processes - Runnable",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "proc_run",
       "precision": "default"
      }
     ]
    }
   ]
  }
 ]
}