{
 "title": "System - Home",
 "tags": [
  "home",
  "system"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Overview - Averages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Logical CPU Count Per Server",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "avg",
     "app": "HOST",
     "downsampleAggregator": "avg",
     "metric": "cpu_num",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Total Memory Per Server",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "format": "kbytes",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "avg",
     "app": "HOST",
     "downsampleAggregator": "avg",
     "metric": "mem_total",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Total Disk Space Per Server",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "format": "gbytes",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "avg",
     "app": "HOST",
     "downsampleAggregator": "avg",
     "metric": "disk_total",
     "precision": "default"
    }
   ]
  },
  { "title": "Overview - Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Logical CPU Count Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "sum",
     "app": "HOST",
     "downsampleAggregator": "avg",
     "metric": "cpu_num",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 5 },
   "format": "kbytes",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "sum",
     "app": "HOST",
     "downsampleAggregator": "avg",
     "metric": "mem_total",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Total Disk Space",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 5 },
   "format": "gbytes",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "sum",
     "app": "HOST",
     "downsampleAggregator": "avg",
     "metric": "disk_total",
     "precision": "default"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization - Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "cpu_user",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "cpu_system",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "cpu_nice",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "cpu_idle",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "cpu_wio",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "cpu_intr",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "cpu_sintr",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "cpu_steal",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "System Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Load - Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "load_one_minute",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "load_one",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "load_five_minutes",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "load_five",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "load_fifteen_minutes",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "load_fifteen",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory - Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "mem_used",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "mem_free",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "mem_cached",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "mem_buffered",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "mem_shared",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Memory - Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "aggregator": "sum",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "mem_used",
       "precision": "default"
      },
      {
       "aggregator": "sum",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "mem_free",
       "precision": "default"
      },
      {
       "aggregator": "sum",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "mem_cached",
       "precision": "default"
      },
      {
       "aggregator": "sum",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "mem_buffered",
       "precision": "default"
      },
      {
       "aggregator": "sum",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "mem_shared",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Utilization - Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "gbytes" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "disk_used",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "disk_free",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Disk Utilization - Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "gbytes" }
     ],
     "targets": [
      {
       "aggregator": "sum",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "disk_used",
       "precision": "default"
      },
      {
       "aggregator": "sum",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "disk_free",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk IO - Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "read_count",
       "precision": "default",
       "transform": "rate"
      },
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "write_count",
       "precision": "default",
       "transform": "rate"
      },
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "read_bytes",
       "precision": "default",
       "transform": "rate"
      },
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "write_bytes",
       "precision": "default",
       "transform": "rate"
      }
     ]
    },
    {
     "title": "Disk IO - Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "read_bytes",
       "precision": "default",
       "transform": "rate"
      },
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "write_bytes",
       "precision": "default",
       "transform": "rate"
      }
     ]
    },
    {
     "title": "Disk IO - Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "aggregator": "sum",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "read_bytes",
       "precision": "default",
       "transform": "rate"
      },
      {
       "aggregator": "sum",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "write_bytes",
       "precision": "default",
       "transform": "rate"
      }
     ]
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network IO - Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "bytes_in",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "bytes_out",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network IO - Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "aggregator": "sum",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "bytes_in",
       "precision": "default"
      },
      {
       "aggregator": "sum",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "bytes_out",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Network Packets - Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "pkts_in",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "pkts_out",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "Swap / Num Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Swap Space - Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "swap_free",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "swap_total",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Num Processes - Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "proc_run",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "app": "HOST",
       "downsampleAggregator": "avg",
       "metric": "proc_total",
       "precision": "default"
      }
     ]
    }
   ]
  }
 ]
}